@echo off
echo Starting Trinetra Backend Server...
cd trinetra-backend
echo Checking if port 5000 is available...
netstat -ano | findstr :5000
if %errorlevel% == 0 (
    echo Port 5000 is in use, killing existing process...
    for /f "tokens=5" %%a in ('netstat -ano ^| findstr :5000') do taskkill /PID %%a /F
    timeout /t 2
)
echo Starting server...
node server.js